package search.twitter.org.twittermediasearchapplication.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import search.twitter.org.twittermediasearchapplication.db.TweetInformation;

import search.twitter.org.twittermediasearchapplication.db.TweetInformationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tweetInformationDaoConfig;

    private final TweetInformationDao tweetInformationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tweetInformationDaoConfig = daoConfigMap.get(TweetInformationDao.class).clone();
        tweetInformationDaoConfig.initIdentityScope(type);

        tweetInformationDao = new TweetInformationDao(tweetInformationDaoConfig, this);

        registerDao(TweetInformation.class, tweetInformationDao);
    }
    
    public void clear() {
        tweetInformationDaoConfig.getIdentityScope().clear();
    }

    public TweetInformationDao getTweetInformationDao() {
        return tweetInformationDao;
    }

}
