package search.twitter.org.twittermediasearchapplication.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TWEET_INFORMATION".
 */
public class TweetInformation {

    private String imgUrl;
    private String imgDesc;
    private String imgProfileUrl;
    private String userName;
    private String screenName;
    private String profileUrl;
    private String tweetUrl;

    public TweetInformation() {
    }

    public TweetInformation(String imgUrl, String imgDesc, String imgProfileUrl, String userName, String screenName, String profileUrl, String tweetUrl) {
        this.imgUrl = imgUrl;
        this.imgDesc = imgDesc;
        this.imgProfileUrl = imgProfileUrl;
        this.userName = userName;
        this.screenName = screenName;
        this.profileUrl = profileUrl;
        this.tweetUrl = tweetUrl;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getImgDesc() {
        return imgDesc;
    }

    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc;
    }

    public String getImgProfileUrl() {
        return imgProfileUrl;
    }

    public void setImgProfileUrl(String imgProfileUrl) {
        this.imgProfileUrl = imgProfileUrl;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    public String getProfileUrl() {
        return profileUrl;
    }

    public void setProfileUrl(String profileUrl) {
        this.profileUrl = profileUrl;
    }

    public String getTweetUrl() {
        return tweetUrl;
    }

    public void setTweetUrl(String tweetUrl) {
        this.tweetUrl = tweetUrl;
    }

}
